### ISSUE TITLE
Help with selenium video in gitlab, please

### ISSUE THREAD

**Issue by alexandremariano4** [alb3ric/ToastTest#1]
Hi friend, sorry for the inconvenience, but I've been having this situation for a while and I saw that you might have the answer due to this issue you opened earlier in selenium/video: https://github.com/SeleniumHQ/docker-selenium/issues/1868

I have this pipeline 

```yaml
stages:
  - "e2e"


e2e:
  image: python
  stage: e2e
  cache: []
  services:
    - name: selenium/standalone-chrome
      alias: browser
    - name: selenium/video
      alias: video


  variables:
    FF_NETWORK_PER_BUILD: "true"
    SE_VIDEO_FOLDER: "/builds"
    SE_VIDEO_FILE_NAME: 'video.mp4'
    DISPLAY_CONTAINER_NAME: browser

  before_script: 
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip3 install poetry
    - poetry install --only main
    - cd project/

  script:
    - python test.py

  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/evidency
    - cp -r /builds/video.mp4 ${CI_PROJECT_DIR}/evidency

  artifacts:
    when: on_failure
    paths:
      - ./evidency
    expire_in: 1 week
    
 ```

However, the video that is generated as evidence is small (256KB), and it is not possible to run it, I would like to know if you have come to any conclusion on how to solve this without having to use docker:dind
